FROM maven:3.8.4-openjdk-17
LABLE maintainer="Gayatri Dwarkunde<gayatridwarkunde10@gmail.com>"" 
COPY ./opt/
WORKDIR /opt
RUN mvn clean package
WorkDIR target/
expose 8080
ENTRYPOINT ["java","-jar"]
CMD ["student-registration-backend-0.0.1-SNAPSHOT.jar"]

