 appipVersion: v1
 kind: Pod
 metadata:
  name: nginxnxp-pod
  labels:
    app: nginxnxp
 spec:
  containers:
  - name: nginxcont
    image: nginx:latest
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginxnxp
spec:
  selector:
    app: nginxnxp
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80